"""Write voices.ily from the music data (data.py, gen.py from the first edition).

    python3 build_voices.py      (run in this directory)

Changes from the first edition's build_voices.py (principles 5.7):
the longs of the source at the ends of the endings (Tenor in every ending,
Medius at the end of each second ending) are printed as longs, scaled to
the breve they fill; the editorial fermata is dropped. Notation uses the
house signs (\\fi, \\sup, \\divTie); the Tenor's text is editorial and set
in italics (\\edText, music/engraving.ily).
"""
import contextlib, io
with contextlib.redirect_stdout(io.StringIO()):
    from data import *

# Longs of the source (critical notes 16, 19 T; 19 M 1; 33, 36 T).
for v, endings in (('T', (1, 2, 4, 5)), ('M', (2, 5))):
    for k in endings:
        VOICES[v][k][-1]['fl'] += 'L'

def sect(v):
    b1, a1, b2, c1, c2, c3 = VOICES[v]
    mus = (f"\\repeat volta 2 {{ {ly_notes(b1)} }}\n"
           f"  \\alternative {{ {{ {ly_notes(a1)} }} {{ {ly_notes(b2)} }} }}\n"
           f"  \\repeat volta 2 {{ {ly_notes(c1)} }}\n"
           f"  \\alternative {{ {{ {ly_notes(c2)} }} {{ {ly_notes(c3)} \\bar \"|.\" }} }}")
    lyr = ' '.join(ly_lyrics(x) for x in (b1, a1, b2, c1, c2, c3))
    return mus, lyr

HEAD = """%% Plaude euge theotocos: voice data, generated by build_voices.py from
%% data.py. Do not edit by hand. Pitch as in the edition (final D, one flat,
%% both editorial); note values of Leipzig Ms 1236. Divided notes carry a
%% dashed tie and take their own syllable, so ties make no melisma here.
"""
out = [HEAD]
for v, name in (('D', 'discantus'), ('M', 'medius'), ('T', 'tenor')):
    m, l = sect(v)
    ed = '\\edText ' if v == 'T' else ''
    out.append(f"{name}Notes = {{\n  \\set melismaBusyProperties = #'()\n  {m}\n}}\n"
               f"{name}Words = \\lyricmode {{\n  {ed}{l}\n}}\n")
open('voices.ily', 'w').write('\n'.join(out))
