import re
from fractions import Fraction as F
from underlay import U
CANON={'A':'nunc scio vere quia misit dominus angelum suum et eripuit me de manu herodis et de omni exspectatione plebis iudaeorum'.split(),
       'D':'gloria patri et filio et spiritui sancto sicut erat in principio et nunc et semper et in saecula saeculorum amen'.split()}
src=open('choral.ily').read()
NAMES=['soprano','alto','tenor','bassus']
def bars_of(name):
    body=re.search(name+r'\s*=\s*\{(.*?)\n\}',src,re.S).group(1)
    lines=[l for l in body.split('\n') if l.strip()]
    bars=[]
    for l in lines:
        code=l.split('%')[0].strip()
        if not code: continue
        for seg in code.split('|'):
            seg=seg.strip()
            if not seg: continue
            m=re.fullmatch(r'R1\*(\d+)',seg)
            if m: bars+=['R1']*int(m.group(1)); continue
            bars.append(seg)
    return bars
def toks(bar):
    return re.findall(r"\\ficta|\\ed|[a-gr](?:is|es)?[',]*\d+\.?~?|R1",bar)
def dur(t):
    m=re.search(r'(\d+)(\.?)',t); d=F(1,int(m.group(1)))
    return d*F(3,2) if m.group(2) else d
def onsets(bars):
    res=[]; prevtie=False
    for bi,b in enumerate(bars):
        for t in toks(b):
            if t.startswith('\\'): continue
            if t[0] in 'rR': prevtie=False; continue
            if not prevtie: res.append((bi+1,t))
            prevtie=t.endswith('~')
    return res
out={}
for n in NAMES:
    bars=bars_of(n); assert len(bars)==88,(n,len(bars))
    for sec,(a,b) in {'A':(0,56),'D':(56,88)}.items():
        ons=onsets(bars[a:b])
        und=U[n,sec]
        assert max(und)<=len(ons),(n,sec,max(und),len(ons))
        # warnings
        for i,s in und.items():
            bar,t=ons[i-1]
            if dur(t)<F(1,4):
                prev=ons[i-2][1] if i>1 else ''
                ok=dur(t)==F(1,8) and prev.endswith('4.')   # semiminim after a dotted minim (principles 10.1)
                print('semiminim after dotted minim' if ok else 'SHORT',n,sec,'bar',bar+a,i,s,t)
        if len(ons) not in und: print('LAST NOTE UNSYLLABLED',n,sec,len(ons))
        # lyric string
        lyr=[]; 
        keys=sorted(und)
        # italicise text repetitions (the 'ij' convention): walk the canonical text
        canon=CANON[sec]; p=0; ital={}; word=[]
        for i in keys:
            word.append(i)
            if not und[i].endswith('-'):
                w=''.join(und[j].rstrip('-') for j in word).strip(',.:;').lower()
                if p<len(canon) and canon[p]==w: p+=1; it=False
                elif p+1<len(canon) and canon[p] in ('et','in','de') and canon[p+1]==w:
                    print('SKIP',n,sec,canon[p],'(principles 10.13)'); p+=2; it=False   # light word left out
                else: it=True
                for j in word: ital[j]=it
                word=[]
        for k,i in enumerate(keys):
            s=und[i]; nxt=keys[k+1] if k+1<len(keys) else len(ons)+1
            cont=s.endswith('-'); word=s.rstrip('-')
            pre='\\rep ' if ital.get(i) else ''
            lyr.append(pre+word+(' --' if cont else ''))
            mel=nxt-i-1
            if mel and not cont: lyr.append('__')
            lyr+=['_']*mel
        out[n,sec]=(' '.join(bars[a:b]), ' '.join(lyr))
        print(n,sec,'onsets',len(ons),'syll',len(und))

# ---- write voices.ily (values doubled: choral.ily keeps those of the tablature)
names={'soprano':'cantus','alto':'altus','tenor':'tenor','bassus':'bassus'}
lines=['%% Generated by build.py from choral.ily and underlay.py. Do not edit by hand.\n'
       '%% Note values are doubled from choral.ily (tablature values). \\fi, \\ed, \\cf, \\rep come\n'
       '%% from the house; \\fin from engraving.ily.\n']
for v,n in names.items():
    for sec,lab in (('A','Ant'),('D','Dox')):
        music,lyr=out[v,sec]
        lines.append(f'{n}{lab} = \\shiftDurations #-1 #0 {{ {music} }}\n'.replace('\\ficta','\\fi'))
        lines.append(f'{n}{lab}Text = \\lyricmode {{ {lyr} }}\n')
open('voices.ily','w').write('\n'.join(lines))
