\version "2.24.0"
%% Nunc scio vere — the score: antiphon, psalm verse in chant, Gloria Patri.
%% Content only; style is in house/lilypond/pol-ren.ily. The music data are
%% generated by build.py (choral.ily + underlay.py -> voices.ily).
%% score-performance.ly includes this file (same pitch, larger staff).
\include "pol-ren.ily"
\include "engraving.ily"
\include "voices.ily"

%% No incipits: the source is a tablature. Voice names, clefs and the
%% mensuration sign are editorial (square brackets in the critical edition).
prEditorialNames = ##t
prEditorialSign = ##t
%% Note values are twice those of the tablature (critical text, Pitch and
%% note values): a semibreve here stands for a minim there.
prValues = \prEquiv 1 2 "of the tablature"

\prSection #'Ant #1
\score {
  \prScore <<
    \prStaff "Cantus" "C." {} "treble"   "" { \rubric "Antiphona" \cantusAnt } \cantusAntText
    \prStaff "Altus"  "A." {} "treble"   "" \altusAnt  \altusAntText
    \prStaff "Tenor"  "T." {} "treble_8" "" \tenorAnt  \tenorAntText
    \prStaff "Bassus" "B." {} "bass"     "" { \bassusAnt \bar "||" } \bassusAntText
  >>
  \layout { $(pr-layout) }
}

\prSection #'Psalm #0
\score {
  <<
    \new Staff \with \prChantStaff \with { instrumentName = "℣." } {
      \new Voice = "psalm" {
        \rubric "Psalmus. Tonus iii."
        \clef "treble_8" \cadenzaOn \key c \major
        g4 a( c') c' c' c' c' c' \bar "'"
        c' d' c' c' b( a) c'( c' c') \bar "|"
        b( g) a( c') c' c' c' c' c' c' c' c' c'2 \bar "'"
        c'4 c' c' c' c'( c' b) a( g) a b g( a2) \bar "||"
      }
    }
    \new Lyrics \with \prChantLyrics \lyricsto "psalm" {
      Dó -- mi -- ne pro -- bá -- sti me,
      et co -- gno -- ví -- sti "me: *"
      tu co -- gno -- ví -- sti ses -- si -- ó -- nem me -- am,
      et re -- sur -- re -- cti -- ó -- nem me -- am.
    }
  >>
  \layout { $(pr-layout) }
}

\prSection #'Dox #57
\score {
  \prScore <<
    \prStaff "Cantus" "C." {} "treble"   "" { \set Score.currentBarNumber = #57 \rubric "Gloria Patri" \cantusDox } \cantusDoxText
    \prStaff "Altus"  "A." {} "treble"   "" \altusDox  \altusDoxText
    \prStaff "Tenor"  "T." {} "treble_8" "" \tenorDox  \tenorDoxText
    \prStaff "Bassus" "B." {} "bass"     "" { \bassusDox \bar "|." \rubricEnd "Repetitur antiphona Nunc scio vere." } \bassusDoxText
  >>
  \layout { $(pr-layout) }
}
