# Build voices.ily from the Marchesano MusicXML (M), transposed up a major third
# to the inferred written pitch (final A, no signature) and with note values doubled.
import music21 as m
from fractions import Fraction as F

SRC='/home/claude/vox/mxl/Vox_in_rama.xml'
s=m.converter.parse(SRC).transpose('M3')
names=['cantus','altus','tenor','bassus']
DUR={F(8):'\\breve',F(6):'1.',F(4):'1',F(3):'2.',F(2):'2',F(3,2):'4.',F(1):'4',F(3,4):'8.',F(1,2):'8',F(1,4):'16',F(12):'\\breve.',F(16):'\\longa'}

def lyname(p):
    step=p.step.lower(); acc={'#':'is','-':'es','':''}[p.accidental.modifier if p.accidental else '']
    o=p.octave-3
    return step+acc+("'"*o if o>0 else ","*(-o))

def events(part):
    """merge tied notes; return list of (offset, ql(doubled), pitch|None, lyric, syllabic)"""
    ev=[]
    for n in part.flatten().notesAndRests:
        off=F(n.offset).limit_denominator(64)*2; ql=F(n.quarterLength).limit_denominator(64)*2
        if n.isRest:
            if ev and ev[-1][2] is None: ev[-1][1]+=ql
            else: ev.append([off,ql,None,None,None,False])
            continue
        tie_in = n.tie is not None and n.tie.type in ('stop','continue')
        lyr = n.lyrics[0] if n.lyrics else None
        if tie_in and ev and ev[-1][2] is not None and ev[-1][2].ps==n.pitch.ps and ev[-1][5]:
            ev[-1][1]+=ql
            ev[-1][5] = n.tie.type=='continue'
        else:
            ev.append([off,ql,n.pitch,lyr.text if lyr else None,lyr.syllabic if lyr else None,
                       n.tie is not None and n.tie.type=='start'])
    return ev

# Readings of the 1611 Tenor (T) that differ from M, and notational features of T
PITCH_FIX={('tenor',42):'E4',
           ('altus',52):'A4',('altus',53):'C5',('altus',54):'D5',('altus',55):'E5'}  # A bars 17-18: octave error in parent (emended)                       # T: e' without flat (M, N: e-flat')
SUGGEST={'tenor':{20,21,76,97}}                     # sharps not printed in T: editorial
LIG={'tenor':[(42,43),(50,51),(81,82)]}             # ligatures cum opposita proprietate in T
COLOR={'tenor':{51}}                                # blackened note in T
out=['%% Generated by build_voices.py — do not edit by hand','']
data={}
for nm,p in zip(names,s.parts):
    ev=events(p)
    for (v,i),pn in PITCH_FIX.items():
        if v==nm: ev[i][2]=m.pitch.Pitch(pn)
    data[nm]=ev
    toks=[]
    ligstart={a for a,b in LIG.get(nm,[])}; ligend={b for a,b in LIG.get(nm,[])}
    last=max(i for i,e in enumerate(ev) if e[2] is not None)
    for idx,(off,ql,pit,lyr,syl,_) in enumerate(ev):
        pre=''; post=''
        if idx in SUGGEST.get(nm,()): pre='\\once \\set suggestAccidentals = ##t '
        if idx in COLOR.get(nm,()): post+='^\\colorMark'
        if idx in ligstart: pre='\\[ '+pre
        if idx in ligend: post+='\\]'
        if idx==last:
            fr=ql/16; toks.append(pre+lyname(pit)+f'\\longa*{fr.numerator}/{fr.denominator}'+post); continue
        if ql not in DUR:
            # split into representable pieces (tie for notes)
            parts=[]; rem=ql
            for d in sorted(DUR,reverse=True):
                while rem>=d: parts.append(d); rem-=d
            assert rem==0,(nm,off,ql)
            if pit is None: toks.append(' '.join('r'+DUR[d] for d in parts))
            else: toks.append('~ '.join(lyname(pit)+DUR[d] for d in parts)); print('TIE kept',nm,'at half-offset',float(off)/2,ql)
        else:
            toks.append(pre+('r' if pit is None else lyname(pit))+DUR[ql]+post)
    out.append(f'{nm}Notes = {{ '+' '.join(toks)+' \\bar "|." }')
open('voices_raw.ily','w').write('\n'.join(out)+'\n')
import json
json.dump({k:[[str(e[0]),str(e[1]),e[2].nameWithOctave if e[2] else None,e[3],e[4]] for e in v] for k,v in data.items()},open('events.json','w'),indent=0)
for k,v in data.items(): print(k, len(v), 'total', float(sum(e[1] for e in v)))
